// data json object
const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: './images/p1.jpg',
            price: 299,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: './images/p2.jpg',
            price: 389,
            brand: 'Adidas',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Levis Slim Shirt',
            category: 'Shirts',
            image: './images/p3.jpg',
            price: 289,
            brand: 'Levis',
            rating: 3,
            numReviews: 8,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: './images/p4.jpg',
            price: 499,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Adidas Slim Pant',
            category: 'Pants',
            image: './images/p5.jpg',
            price: 599,
            brand: 'Adidas',  
            rating: 5,
            numReviews: 5,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Levis Slim Pant',
            category: 'Pants',
            image: './images/p6.jpg',
            price: 499,
            brand: 'Levis',
            rating: 4,
            numReviews: 8 ,
            description: 'high quality product',
        },
    ],
};

export default data;